# Generated by Django 5.0.2 on 2024-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="profile_pics/default.png", upload_to="profile_pics"),
        ),
    ]
