# Generated by Django 5.0.2 on 2024-04-05 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(help_text="Name of the task category", max_length=100, unique=True)),
                ("is_default", models.BooleanField(default=False, help_text="Is this a default category?")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of the task", max_length=200)),
                (
                    "completed",
                    models.CharField(
                        choices=[
                            ("TO_DO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("BLOCKED", "Blocked"),
                        ],
                        help_text="Task status",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Date of task create")),
                ("deadline", models.DateTimeField(blank=True, help_text="Deadline of the task", null=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author of the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Task category", on_delete=django.db.models.deletion.CASCADE, to="todo.taskcategory"
                    ),
                ),
            ],
        ),
    ]
