# Generated by Django 5.0.2 on 2024-04-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcategory",
            name="is_default",
            field=models.BooleanField(blank=True, default=False, help_text="Is this a default category?"),
        ),
    ]
