# Generated by Django 5.0.2 on 2024-06-19 16:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("car_make", models.CharField(max_length=100)),
                ("car_model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CarMaintenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=datetime.datetime(2024, 6, 19, 18, 1, 18, 160429))),
                ("service", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="car_maintenance.car")),
            ],
        ),
        migrations.CreateModel(
            name="FuelCosts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("fuel_amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fuel_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mileage", models.IntegerField()),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="car_maintenance.car")),
            ],
        ),
    ]
