# Generated by Django 5.0.2 on 2024-06-19 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="carmaintenance",
            name="date",
            field=models.DateField(default=datetime.datetime(2024, 6, 19, 18, 49, 12, 210258)),
        ),
        migrations.AlterField(
            model_name="fuelcosts",
            name="fuel_amount",
            field=models.DecimalField(decimal_places=2, help_text="in litres", max_digits=5),
        ),
        migrations.AlterField(
            model_name="fuelcosts",
            name="mileage",
            field=models.IntegerField(help_text="in kilometers"),
        ),
    ]
