# Generated by Django 5.0.2 on 2024-06-19 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_maintenance", "0002_alter_car_year_alter_carmaintenance_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmaintenance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 19, 16, 50, 36, 481837, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
