# Generated by Django 5.0.2 on 2024-06-20 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_maintenance", "0003_alter_carmaintenance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmaintenance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
