# Generated by Django 5.0.2 on 2024-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_maintenance", "0004_alter_carmaintenance_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CarMaintenance",
            new_name="CarMaintenanceHistory",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="car_make",
            new_name="carmake",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="car_model",
            new_name="carmodel",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="year",
            new_name="year_of_production",
        ),
        migrations.RenameField(
            model_name="fuelcosts",
            old_name="fuel_amount",
            new_name="fuelamount",
        ),
        migrations.RenameField(
            model_name="fuelcosts",
            old_name="fuel_cost",
            new_name="fuelcost",
        ),
        migrations.RemoveField(
            model_name="fuelcosts",
            name="mileage",
        ),
        migrations.AddField(
            model_name="fuelcosts",
            name="odometer_reading",
            field=models.IntegerField(blank=True, help_text="total mileage in kilometers", null=True),
        ),
    ]
