# Generated by Django 5.0.2 on 2024-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("summary", models.TextField()),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("summary", models.TextField()),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
    ]
