# Generated by Django 5.0.2 on 2024-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[("1", "Terrible"), ("2", "Bad"), ("3", "Okay"), ("4", "Really good!"), ("5", "New favorite!")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
