# Generated by Django 5.0.2 on 2024-06-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="series_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="tom",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Terrible", "Terrible"),
                    ("Bad", "Bad"),
                    ("Okay", "Okay"),
                    ("Really good!", "Really good!"),
                    ("New favorite!", "New favorite!"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Terrible", "Terrible"),
                    ("Bad", "Bad"),
                    ("Okay", "Okay"),
                    ("Really good!", "Really good!"),
                    ("New favorite!", "New favorite!"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="medialibrary.author"
            ),
        ),
    ]
