# Generated by Django 5.0.2 on 2024-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0002_alter_book_published_date_alter_book_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[("1", "Terrible"), ("2", "Bad"), ("3", "Okay"), ("4", "Really good!"), ("5", "New favorite!")],
                max_length=100,
                null=True,
            ),
        ),
    ]
