# Generated by Django 5.0.2 on 2024-06-18 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0003_alter_book_author"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="BookAuthor",
        ),
    ]
