# Generated by Django 5.0.2 on 2024-06-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0003_alter_book_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Terrible", "Terrible"),
                    ("Bad", "Bad"),
                    ("Okay", "Okay"),
                    ("Really good!", "Really good!"),
                    ("New favorite!", "New favorite!"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("Terrible", "Terrible"),
                    ("Bad", "Bad"),
                    ("Okay", "Okay"),
                    ("Really good!", "Really good!"),
                    ("New favorite!", "New favorite!"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
