# Generated by Django 5.0.2 on 2024-06-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0004_alter_book_rating_alter_movie_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Terrible", "Terrible"),
                    ("Bad", "Bad"),
                    ("Okay", "Okay"),
                    ("Really good!", "Really good!"),
                    ("New favorite!", "New favorite!"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
