# Generated by Django 5.0.2 on 2024-06-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medialibrary", "0005_alter_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
